sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: DEPENDENCIES='low'
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 7.0

before_script:
  - phpenv config-add .travis-config.ini || return 0
  - composer self-update

install:
  - yes '' | pecl -q install -f mongo-1.5.8 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - if [ "$DEPENDENCIES" != "low" ]; then composer update --prefer-dist --no-scripts --no-interaction; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest --no-scripts --no-interaction; fi;

script:
  - ./vendor/bin/grumphp run
